language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  before_install:
  - gem install bundler: 2.1.4
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
  app:
  run: rails db:migrate
env:
  global:
    secure: dSmHiTzj79U3z5LzfBIl4FfF/e9ylBbrHJt4/h2hxBj5dS3UxIJVlFFqGRGuLJrifiwBe73PPNCjCqvDSBkNKikvTGnNG93/FBP60deLIop87o0QCn2z1fQhZXhScLKfOS+b0c5ZuhYWpkQh+0hfzGI7LR96QtWqsW3p0dGvBdobMH0kIe0wG0eV9bqt1GIz7BEEz1M3IicpzAL8jD0Trklmt3bXiJzZ8llRcsxMZ92ysbGCqNdPYZ5GT5d2JYZxgU7Ds8ZNIykOYXic2Fz1WBb8yQTONMPUtbL1KKU9zWqS7cnCNMrJZFQnxTx8nR5vbus2rDtCmlfIXjbugtlnmu47mwSxcW0pJ5771c3cWGXiMgd2QjcNjZ6OqXVX7mJ2xZnRPkSm8x9UOtxopNaMnh3dy+zBzlWyoASm+BBfwvs/W+e6U4qnvLq3y/TE6fEmC8e9b48Rejfxjs3S9LQpEP8cXhBZu0nuQ63O5H+/r8FvZuW7Owr3LFIDGHPE4N2i6vAzjyAZM0gcJmHedTrwYogr+kI1D4wXYGWVEUvapAoJy5I6OuAw57+KIQ/akhFzvXJ4PLtajwAsg8kOhk/TSUk1zWoPzOEw3r7qnskITcMa17IwAdx+N2758akS7tcvWLbIq+fmWWtD/KJK2bVR3Ms4Zar634BbCAgslbQPUvo=
